/**
 * Static station metadata for all 145 playable stations.
 * Used to seed the Convex `stations` table.
 *
 * lines: NSL | EWL | CCL | NEL | DTL | TEL
 * zone: North | South | East | West | Central
 * opened: year the station first opened
 * interchange: true if served by 2+ lines
 */

export interface StationMeta {
  name: string;
  lines: string[];
  zone: string;
  opened: number;
  interchange: boolean;
}

export const STATION_DATA: StationMeta[] = [
  // ── North-South Line ─────────────────────────────────────────────────────
  { name: "Marina South Pier",  lines: ["NSL"],         zone: "South",   opened: 2014, interchange: false },
  { name: "Marina Bay",         lines: ["NSL","CCL","TEL"], zone: "South", opened: 1989, interchange: true },
  { name: "Raffles Place",      lines: ["NSL","EWL"],   zone: "Central", opened: 1987, interchange: true },
  { name: "City Hall",          lines: ["NSL","EWL"],   zone: "Central", opened: 1987, interchange: true },
  { name: "Dhoby Ghaut",        lines: ["NSL","CCL","NEL"], zone: "Central", opened: 1987, interchange: true },
  { name: "Somerset",           lines: ["NSL"],         zone: "Central", opened: 1987, interchange: false },
  { name: "Orchard",            lines: ["NSL","TEL"],   zone: "Central", opened: 1987, interchange: true },
  { name: "Newton",             lines: ["NSL","DTL"],   zone: "Central", opened: 1987, interchange: true },
  { name: "Novena",             lines: ["NSL"],         zone: "Central", opened: 1987, interchange: false },
  { name: "Toa Payoh",          lines: ["NSL"],         zone: "Central", opened: 1987, interchange: false },
  { name: "Braddell",           lines: ["NSL"],         zone: "Central", opened: 1987, interchange: false },
  { name: "Bishan",             lines: ["NSL","CCL"],   zone: "Central", opened: 1988, interchange: true },
  { name: "Ang Mo Kio",         lines: ["NSL"],         zone: "North",   opened: 1987, interchange: false },
  { name: "Yio Chu Kang",       lines: ["NSL"],         zone: "North",   opened: 1987, interchange: false },
  { name: "Khatib",             lines: ["NSL"],         zone: "North",   opened: 1988, interchange: false },
  { name: "Yishun",             lines: ["NSL"],         zone: "North",   opened: 1988, interchange: false },
  { name: "Canberra",           lines: ["NSL"],         zone: "North",   opened: 2019, interchange: false },
  { name: "Sembawang",          lines: ["NSL"],         zone: "North",   opened: 1988, interchange: false },
  { name: "Admiralty",          lines: ["NSL"],         zone: "North",   opened: 1996, interchange: false },
  { name: "Woodlands",          lines: ["NSL","TEL"],   zone: "North",   opened: 1996, interchange: true },
  { name: "Marsiling",          lines: ["NSL"],         zone: "North",   opened: 1996, interchange: false },
  { name: "Kranji",             lines: ["NSL"],         zone: "North",   opened: 1996, interchange: false },
  { name: "Yew Tee",            lines: ["NSL"],         zone: "North",   opened: 1996, interchange: false },
  { name: "Choa Chu Kang",      lines: ["NSL"],         zone: "West",    opened: 1990, interchange: false },
  { name: "Bukit Gombak",       lines: ["NSL"],         zone: "West",    opened: 1990, interchange: false },
  { name: "Bukit Batok",        lines: ["NSL"],         zone: "West",    opened: 1990, interchange: false },
  { name: "Jurong East",        lines: ["NSL","EWL"],   zone: "West",    opened: 1988, interchange: true },

  // ── East-West Line ────────────────────────────────────────────────────────
  { name: "Tuas Link",          lines: ["EWL"],         zone: "West",    opened: 2009, interchange: false },
  { name: "Tuas Crescent",      lines: ["EWL"],         zone: "West",    opened: 2017, interchange: false },
  { name: "Gul Circle",         lines: ["EWL"],         zone: "West",    opened: 2017, interchange: false },
  { name: "Joo Koon",           lines: ["EWL"],         zone: "West",    opened: 1996, interchange: false },
  { name: "Pioneer",            lines: ["EWL"],         zone: "West",    opened: 1996, interchange: false },
  { name: "Boon Lay",           lines: ["EWL"],         zone: "West",    opened: 1990, interchange: false },
  { name: "Lakeside",           lines: ["EWL"],         zone: "West",    opened: 1988, interchange: false },
  { name: "Chinese Garden",     lines: ["EWL"],         zone: "West",    opened: 1988, interchange: false },
  { name: "Clementi",           lines: ["EWL"],         zone: "West",    opened: 1988, interchange: false },
  { name: "Dover",              lines: ["EWL"],         zone: "West",    opened: 2001, interchange: false },
  { name: "Buona Vista",        lines: ["EWL","CCL"],   zone: "West",    opened: 1988, interchange: true },
  { name: "Commonwealth",       lines: ["EWL"],         zone: "Central", opened: 1988, interchange: false },
  { name: "Queenstown",         lines: ["EWL"],         zone: "Central", opened: 1988, interchange: false },
  { name: "Redhill",            lines: ["EWL"],         zone: "Central", opened: 1988, interchange: false },
  { name: "Tiong Bahru",        lines: ["EWL"],         zone: "Central", opened: 1988, interchange: false },
  { name: "Outram Park",        lines: ["EWL","NEL","TEL"], zone: "Central", opened: 1988, interchange: true },
  { name: "Tanjong Pagar",      lines: ["EWL"],         zone: "Central", opened: 1988, interchange: false },
  { name: "Lavender",           lines: ["EWL"],         zone: "Central", opened: 1987, interchange: false },
  { name: "Kallang",            lines: ["EWL"],         zone: "Central", opened: 1987, interchange: false },
  { name: "Aljunied",           lines: ["EWL"],         zone: "East",    opened: 1987, interchange: false },
  { name: "Paya Lebar",         lines: ["EWL","CCL"],   zone: "East",    opened: 1989, interchange: true },
  { name: "Eunos",              lines: ["EWL"],         zone: "East",    opened: 1989, interchange: false },
  { name: "Kembangan",          lines: ["EWL"],         zone: "East",    opened: 1989, interchange: false },
  { name: "Bedok",              lines: ["EWL"],         zone: "East",    opened: 1989, interchange: false },
  { name: "Tanah Merah",        lines: ["EWL"],         zone: "East",    opened: 1989, interchange: false },
  { name: "Simei",              lines: ["EWL"],         zone: "East",    opened: 1989, interchange: false },
  { name: "Tampines",           lines: ["EWL","DTL"],   zone: "East",    opened: 1989, interchange: true },
  { name: "Pasir Ris",          lines: ["EWL"],         zone: "East",    opened: 1989, interchange: false },
  { name: "Expo",               lines: ["EWL","DTL"],   zone: "East",    opened: 2001, interchange: true },
  { name: "Changi Airport",     lines: ["EWL"],         zone: "East",    opened: 2002, interchange: false },

  // ── Circle Line ───────────────────────────────────────────────────────────
  { name: "Bayfront",           lines: ["CCL","DTL"],   zone: "South",   opened: 2012, interchange: true },
  { name: "Bras Basah",         lines: ["CCL"],         zone: "Central", opened: 2010, interchange: false },
  { name: "Esplanade",          lines: ["CCL"],         zone: "Central", opened: 2010, interchange: false },
  { name: "Promenade",          lines: ["CCL","DTL"],   zone: "Central", opened: 2010, interchange: true },
  { name: "Nicoll Highway",     lines: ["CCL"],         zone: "Central", opened: 2010, interchange: false },
  { name: "Stadium",            lines: ["CCL"],         zone: "Central", opened: 2010, interchange: false },
  { name: "Mountbatten",        lines: ["CCL"],         zone: "Central", opened: 2010, interchange: false },
  { name: "Dakota",             lines: ["CCL"],         zone: "Central", opened: 2010, interchange: false },
  { name: "MacPherson",         lines: ["CCL","DTL"],   zone: "East",    opened: 2010, interchange: true },
  { name: "Tai Seng",           lines: ["CCL"],         zone: "East",    opened: 2010, interchange: false },
  { name: "Bartley",            lines: ["CCL"],         zone: "East",    opened: 2010, interchange: false },
  { name: "Serangoon",          lines: ["CCL","NEL"],   zone: "East",    opened: 2009, interchange: true },
  { name: "Lorong Chuan",       lines: ["CCL"],         zone: "Central", opened: 2009, interchange: false },
  { name: "Marymount",          lines: ["CCL"],         zone: "Central", opened: 2009, interchange: false },
  { name: "Caldecott",          lines: ["CCL","TEL"],   zone: "Central", opened: 2011, interchange: true },
  { name: "Botanic Gardens",    lines: ["CCL","DTL"],   zone: "Central", opened: 2011, interchange: true },
  { name: "Farrer Road",        lines: ["CCL"],         zone: "Central", opened: 2011, interchange: false },
  { name: "Holland Village",    lines: ["CCL"],         zone: "West",    opened: 2011, interchange: false },
  { name: "one-north",          lines: ["CCL"],         zone: "West",    opened: 2011, interchange: false },
  { name: "Kent Ridge",         lines: ["CCL"],         zone: "West",    opened: 2011, interchange: false },
  { name: "Haw Par Villa",      lines: ["CCL"],         zone: "West",    opened: 2011, interchange: false },
  { name: "Pasir Panjang",      lines: ["CCL"],         zone: "West",    opened: 2011, interchange: false },
  { name: "Labrador Park",      lines: ["CCL"],         zone: "South",   opened: 2011, interchange: false },
  { name: "Telok Blangah",      lines: ["CCL"],         zone: "South",   opened: 2011, interchange: false },
  { name: "HarbourFront",       lines: ["CCL","NEL"],   zone: "South",   opened: 2003, interchange: true },

  // ── North-East Line ───────────────────────────────────────────────────────
  { name: "Clarke Quay",        lines: ["NEL"],         zone: "Central", opened: 2003, interchange: false },
  { name: "Chinatown",          lines: ["NEL","DTL"],   zone: "Central", opened: 2003, interchange: true },
  { name: "Little India",       lines: ["NEL","DTL"],   zone: "Central", opened: 2003, interchange: true },
  { name: "Farrer Park",        lines: ["NEL"],         zone: "Central", opened: 2003, interchange: false },
  { name: "Boon Keng",          lines: ["NEL"],         zone: "Central", opened: 2003, interchange: false },
  { name: "Potong Pasir",       lines: ["NEL"],         zone: "Central", opened: 2003, interchange: false },
  { name: "Woodleigh",          lines: ["NEL"],         zone: "Central", opened: 2011, interchange: false },
  { name: "Kovan",              lines: ["NEL"],         zone: "East",    opened: 2003, interchange: false },
  { name: "Hougang",            lines: ["NEL"],         zone: "East",    opened: 2003, interchange: false },
  { name: "Buangkok",           lines: ["NEL"],         zone: "East",    opened: 2006, interchange: false },
  { name: "Sengkang",           lines: ["NEL"],         zone: "East",    opened: 2003, interchange: false },
  { name: "Punggol",            lines: ["NEL"],         zone: "East",    opened: 2003, interchange: false },
  { name: "Punggol Coast",      lines: ["NEL"],         zone: "East",    opened: 2024, interchange: false },

  // ── Downtown Line ─────────────────────────────────────────────────────────
  { name: "Bukit Panjang",      lines: ["DTL"],         zone: "West",    opened: 2015, interchange: false },
  { name: "Cashew",             lines: ["DTL"],         zone: "West",    opened: 2015, interchange: false },
  { name: "Hillview",           lines: ["DTL"],         zone: "West",    opened: 2015, interchange: false },
  { name: "Hume",               lines: ["DTL"],         zone: "West",    opened: 2024, interchange: false },
  { name: "Beauty World",       lines: ["DTL"],         zone: "West",    opened: 2015, interchange: false },
  { name: "King Albert Park",   lines: ["DTL"],         zone: "West",    opened: 2015, interchange: false },
  { name: "Sixth Avenue",       lines: ["DTL"],         zone: "West",    opened: 2015, interchange: false },
  { name: "Tan Kah Kee",        lines: ["DTL"],         zone: "Central", opened: 2015, interchange: false },
  { name: "Stevens",            lines: ["DTL","TEL"],   zone: "Central", opened: 2015, interchange: true },
  { name: "Rochor",             lines: ["DTL"],         zone: "Central", opened: 2013, interchange: false },
  { name: "Bugis",              lines: ["EWL","DTL"],   zone: "Central", opened: 1989, interchange: true },
  { name: "Downtown",           lines: ["DTL"],         zone: "South",   opened: 2013, interchange: false },
  { name: "Telok Ayer",         lines: ["DTL"],         zone: "Central", opened: 2013, interchange: false },
  { name: "Fort Canning",       lines: ["DTL"],         zone: "Central", opened: 2013, interchange: false },
  { name: "Bencoolen",          lines: ["DTL"],         zone: "Central", opened: 2013, interchange: false },
  { name: "Jalan Besar",        lines: ["DTL"],         zone: "Central", opened: 2013, interchange: false },
  { name: "Bendemeer",          lines: ["DTL"],         zone: "Central", opened: 2013, interchange: false },
  { name: "Geylang Bahru",      lines: ["DTL"],         zone: "East",    opened: 2013, interchange: false },
  { name: "Mattar",             lines: ["DTL"],         zone: "East",    opened: 2013, interchange: false },
  { name: "Ubi",                lines: ["DTL"],         zone: "East",    opened: 2016, interchange: false },
  { name: "Kaki Bukit",         lines: ["DTL"],         zone: "East",    opened: 2016, interchange: false },
  { name: "Bedok North",        lines: ["DTL"],         zone: "East",    opened: 2016, interchange: false },
  { name: "Bedok Reservoir",    lines: ["DTL"],         zone: "East",    opened: 2016, interchange: false },
  { name: "Tampines West",      lines: ["DTL"],         zone: "East",    opened: 2016, interchange: false },
  { name: "Tampines East",      lines: ["DTL"],         zone: "East",    opened: 2016, interchange: false },
  { name: "Upper Changi",       lines: ["DTL"],         zone: "East",    opened: 2016, interchange: false },
  { name: "Xilin",              lines: ["DTL"],         zone: "East",    opened: 2024, interchange: false },
  { name: "Sungei Bedok",       lines: ["DTL","TEL"],   zone: "East",    opened: 2024, interchange: true },

  // ── Thomson-East Coast Line ───────────────────────────────────────────────
  { name: "Woodlands North",    lines: ["TEL"],         zone: "North",   opened: 2020, interchange: false },
  { name: "Woodlands South",    lines: ["TEL"],         zone: "North",   opened: 2020, interchange: false },
  { name: "Springleaf",         lines: ["TEL"],         zone: "North",   opened: 2020, interchange: false },
  { name: "Lentor",             lines: ["TEL"],         zone: "North",   opened: 2020, interchange: false },
  { name: "Mayflower",          lines: ["TEL"],         zone: "North",   opened: 2020, interchange: false },
  { name: "Bright Hill",        lines: ["TEL"],         zone: "North",   opened: 2020, interchange: false },
  { name: "Upper Thomson",      lines: ["TEL"],         zone: "North",   opened: 2020, interchange: false },
  { name: "Napier",             lines: ["TEL"],         zone: "Central", opened: 2021, interchange: false },
  { name: "Orchard Boulevard",  lines: ["TEL"],         zone: "Central", opened: 2021, interchange: false },
  { name: "Great World",        lines: ["TEL"],         zone: "Central", opened: 2021, interchange: false },
  { name: "Havelock",           lines: ["TEL"],         zone: "Central", opened: 2021, interchange: false },
  { name: "Maxwell",            lines: ["TEL"],         zone: "Central", opened: 2021, interchange: false },
  { name: "Shenton Way",        lines: ["TEL"],         zone: "Central", opened: 2021, interchange: false },
  { name: "Gardens by the Bay", lines: ["TEL"],         zone: "South",   opened: 2022, interchange: false },
  { name: "Tanjong Rhu",        lines: ["TEL"],         zone: "East",    opened: 2022, interchange: false },
  { name: "Katong Park",        lines: ["TEL"],         zone: "East",    opened: 2022, interchange: false },
  { name: "Tanjong Katong",     lines: ["TEL"],         zone: "East",    opened: 2022, interchange: false },
  { name: "Marine Parade",      lines: ["TEL"],         zone: "East",    opened: 2022, interchange: false },
  { name: "Marine Terrace",     lines: ["TEL"],         zone: "East",    opened: 2022, interchange: false },
  { name: "Siglap",             lines: ["TEL"],         zone: "East",    opened: 2022, interchange: false },
  { name: "Bayshore",           lines: ["TEL"],         zone: "East",    opened: 2023, interchange: false },
  { name: "Bedok South",        lines: ["TEL"],         zone: "East",    opened: 2023, interchange: false },
];
